plugins {
    id 'java-library'
}

dependencies {
    api 'jakarta.persistence:jakarta.persistence-api'
    api 'org.springframework.data:spring-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-validation'

    // firebase
    implementation 'com.google.firebase:firebase-admin:9.7.1'

    api project(':common')
    api 'org.projectlombok:lombok'

}

jar {
    enabled = true
}
